"""Load crude datasets from the refreshed store, or fall back to the synthetic sample.

Real and synthetic data are never mixed: the store is used only when its
core tables (daily prices and weekly balances) are present; otherwise every
crude page runs on the clearly-labelled synthetic sample.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

import pandas as pd

from src.config import SAMPLE_DIR
from src.crude.config import EIA_DAILY, EIA_WEEKLY, T_COT, T_DAILY, T_WEEKLY
from src.data_store import STORE_DIR, read_status, read_table

CRUDE_SAMPLE_NOTICE = (
    "SYNTHETIC SAMPLE DATA: crude prices, balances and positioning generated by "
    "scripts/generate_sample_crude.py. Not real market data. Run scripts/daily_update.py "
    "(or the scheduled GitHub Action) with an EIA_API_KEY to load real data."
)
COT_COLUMNS = ["open_interest", "mm_long", "mm_short", "mm_spread", "producer_long", "producer_short", "swap_long", "swap_short"]


@dataclass
class CrudeData:
    daily: pd.DataFrame
    weekly: pd.DataFrame
    cot: pd.DataFrame
    source: Literal["store", "sample"]
    notices: list[str] = field(default_factory=list)
    status: dict = field(default_factory=dict)

    @property
    def is_sample(self) -> bool:
        return self.source == "sample"

    @property
    def has_cot(self) -> bool:
        return not self.cot.empty


def _ensure(df: pd.DataFrame | None, columns, index_name: str) -> pd.DataFrame:
    if df is None:
        df = pd.DataFrame(index=pd.DatetimeIndex([], name=index_name))
    for c in columns:
        if c not in df:
            df[c] = float("nan")
    df.index.name = index_name
    return df[list(columns)].astype(float)


def _usable(daily: pd.DataFrame | None, weekly: pd.DataFrame | None) -> bool:
    if daily is None or weekly is None:
        return False
    return (daily.get("wti_spot", pd.Series(dtype=float)).notna().sum() > 250
            and weekly.get("crude_stocks", pd.Series(dtype=float)).notna().sum() > 52 * 6)


def load_crude_data(store_root: Path | None = None, sample_root: Path | None = None) -> CrudeData:
    store_root = store_root or STORE_DIR
    sample_root = sample_root or SAMPLE_DIR
    daily, weekly, cot = (read_table(t, store_root) for t in (T_DAILY, T_WEEKLY, T_COT))
    status = read_status(store_root / "status.json")
    notices: list[str] = []
    if _usable(daily, weekly):
        source = "store"
        if cot is None or cot.empty:
            notices.append("CFTC positioning data not in the store yet; positioning views are disabled.")
        futures_end = daily["cl1"].dropna().index.max() if "cl1" in daily and daily["cl1"].notna().any() else None
        if futures_end is not None and futures_end < daily.index.max() - pd.Timedelta(days=30):
            notices.append(
                f"EIA stopped publishing NYMEX futures prices after {futures_end:%d %b %Y}; the official curve history "
                "ends there. The live curve comes from Yahoo Finance (unofficial)."
            )
    else:
        source = "sample"
        daily, weekly, cot = (read_table(t, sample_root) for t in (T_DAILY, T_WEEKLY, T_COT))
        notices.insert(0, CRUDE_SAMPLE_NOTICE)
        status = {}
    return CrudeData(
        daily=_ensure(daily, EIA_DAILY, "date"),
        weekly=_ensure(weekly, EIA_WEEKLY, "date"),
        cot=_ensure(cot, COT_COLUMNS, "report_date"),
        source=source,
        notices=notices,
        status=status,
    )
