"""Page 7 - Daily Trading Brief (deterministic, rule-based)."""

from __future__ import annotations

import pandas as pd
import streamlit as st

from src import charts
from src.market_commentary import generate_daily_brief
from src.views.common import Ctx, eur, gw, page_header


def render(ctx: Ctx) -> None:
    page_header(ctx, "Daily Trading Brief", "Internal-style market note generated by explicit rules - no LLM")
    dates = sorted(ctx.view["date"].unique())
    if not dates:
        st.warning("No data in the selected window.")
        return
    picked = st.date_input("Delivery day", value=pd.Timestamp(dates[-1]).date(),
                           min_value=pd.Timestamp(dates[0]).date(), max_value=pd.Timestamp(dates[-1]).date(),
                           format="YYYY-MM-DD", key="brief_date")
    day_ts = pd.Timestamp(picked)

    brief = generate_daily_brief(ctx.feat, ctx.zone, day_ts, ctx.data.zone_prices, ctx.data.flows)
    s = brief.stats

    left, right = st.columns([3, 2])
    with left:
        with st.container(border=True):
            st.markdown(f"### {brief.title}")
            st.markdown(f"**{brief.headline}**")
            for i, (name, text) in enumerate(brief.sections.items(), start=1):
                st.markdown(f"**{i}. {name}**")
                st.markdown(text)
        st.download_button("Download brief (.md)", brief.to_markdown(), file_name=f"brief_{ctx.zone}_{picked}.md",
                           mime="text/markdown")
    with right:
        k1, k2 = st.columns(2)
        k1.metric("Baseload", eur(s["base"], 1),
                  delta=f"{s['base'] - s['prev_base']:+.1f} d/d" if pd.notna(s["prev_base"]) else None, border=True)
        k2.metric("Peak / off-peak", f"{eur(s['peak'])} / {eur(s['offpeak'])}" if pd.notna(s["peak"]) else f"— / {eur(s['offpeak'])}",
                  border=True)
        k3, k4 = st.columns(2)
        k3.metric("Residual demand", gw(s["rd"]),
                  delta=f"{(s['rd'] - s['avg30_rd']) / 1000:+.1f} GW vs 30d" if pd.notna(s["avg30_rd"]) else None,
                  delta_color="inverse", border=True)
        k4.metric("Resid. demand forecast error", gw(s["rd_err"], 2), border=True,
                  help="Actual minus day-ahead forecast. Positive = system shorter than the auction assumed.")
        st.caption("How the note is built: realised data for the day, comparisons against the previous 30 days only, "
                   "and day-ahead forecasts for the next day (published on the day). No later data is used - this is "
                   "covered by a unit test.")

    feat = ctx.feat
    day = feat[feat["date"] == day_ts]
    prev = feat[feat["date"] == day_ts - pd.Timedelta(days=1)]
    st.plotly_chart(charts.day_profile(day, prev), key="brief_profile")
