"""Page 9 - Methodology, assumptions and data provenance."""

from __future__ import annotations

import streamlit as st

from src.data_loader import sample_metadata
from src.views.common import Ctx


def render(ctx: Ctx) -> None:
    st.title("Methodology & Data")
    st.markdown(
        "> This project is designed to connect market fundamentals to trading-style decision-making. "
        "It is not a black-box price prediction model."
    )

    st.subheader("Data source in use")
    if ctx.data.is_sample:
        meta = sample_metadata()
        st.warning(meta.get("notice", "Synthetic sample data."), icon="🧪")
        st.markdown(
            f"""
- Generated by `scripts/generate_sample_data.py` (seed {meta.get('seed', 'n/a')}, version {meta.get('generator_version', 'n/a')}).
- Period: {meta.get('period_local', ['?', '?'])[0]} to {meta.get('period_local', ['?', '?'])[1]} (local market time).
- Weather-driven load, wind and solar; day-ahead forecasts with autocorrelated errors; prices from per-zone merit-order
  curves built on synthetic gas/carbon paths; a simplified market-coupling loop for flows and spreads.
- The price-setting residual demand includes {meta.get('dgp_assumptions', {}).get('forecast_bias_anticipated_by_market', 'part')}
  of each day's systematic forecast bias, mimicking market forecasts that are better than the published TSO forecast.
- Gaps were injected deliberately to exercise the data-quality checks.
"""
        )
    else:
        st.success("ENTSO-E Transparency Platform (REST API). Raw XML responses are cached in `data/raw/entsoe_cache.sqlite`.")

    st.subheader("Data quality for the loaded window")
    st.dataframe(ctx.data.quality.to_frame())
    st.caption("Gaps of up to 3 hours are linearly interpolated; longer gaps stay missing and are excluded from statistics.")

    st.subheader("Key definitions")
    st.markdown(
        """
| Concept | Definition |
|---|---|
| Residual demand | load − wind − solar (actual or day-ahead forecast) |
| Forecast error | actual − day-ahead forecast; *residual-demand error* = load error − (wind + solar) error |
| Peak / off-peak | Mon–Fri 08:00–20:00 local / all other hours |
| Spike | price above a chosen percentile of the selected period, or above an absolute threshold |
| Volatility | std of hour-on-hour price changes in €/MWh (absolute, because prices can be negative) |
| Volatility regime | trailing 7-day volatility vs the 33rd/67th percentiles of its own past |
| Market day | local (CET/CEST) calendar day: 23 hours in March, 25 in October |
"""
    )

    st.subheader("Honesty rules")
    st.markdown(
        """
1. **No fake live results** - the data source is shown on every page; synthetic data is labelled as such.
2. **No look-ahead** - signals use an explicit information set (see Signal Lab) enforced by perturbation tests.
3. **Costs always on** - every traded MWh pays a configurable cost.
4. **No fitting** - signal rules are fixed thresholds, not optimised parameters.
5. **Proxy PnL is labelled as a proxy** - it measures calls versus yesterday's price, not executable trades.
"""
    )

    st.subheader("Known limitations")
    st.markdown(
        """
- No fuel (TTF), carbon (EUA) or outage (REMIT) data - the main non-weather price drivers are missing.
- ENTSO-E day-ahead forecasts are a proxy for what traders actually see before gate closure.
- Hourly resolution: since 1 October 2025 the day-ahead market clears in 15-minute periods; this project averages them to hourly.
- Physical flows are not the same as commercial schedules, and Core capacities are flow-based rather than fixed NTCs.
- The backtest has no market impact, no position limits and a single fixed clip size.
"""
    )
