"""Load market data from the ENTSO-E API or the bundled synthetic sample.

The rest of the project only ever sees a `MarketData` object, so analytics
code does not care where the numbers came from. The *source* is always
carried along and shown in the UI: sample data is labelled as synthetic
everywhere it appears.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from datetime import date
from functools import lru_cache
from typing import Literal

import pandas as pd

from src.config import SAMPLE_DIR, ZONES, Settings, get_settings, neighbours
from src.data_cleaning import (
    CORE_COLUMNS,
    DataQualityReport,
    clean_market_frame,
    to_hourly,
)
from src.data_store import read_table, table_path
from src.entsoe_client import EntsoeClient, EntsoeError, ResponseCache
from src.utils import market_day_bounds, to_market_tz

logger = logging.getLogger(__name__)

SourceName = Literal["sample", "entsoe", "store"]
POWER_STORE_ZONES = [z for z, cfg in ZONES.items() if cfg.in_sample]
SAMPLE_NOTICE = (
    "SYNTHETIC SAMPLE DATA: generated by scripts/generate_sample_data.py to mimic ENTSO-E data. "
    "It is not real market data. Add an ENTSO-E token in .env to analyse real markets."
)


@dataclass
class MarketData:
    zone: str
    frame: pd.DataFrame  # hourly, market time, CORE_COLUMNS
    flows: pd.DataFrame  # long: timestamp, from_zone, to_zone, flow_mw (>= 0 per direction)
    zone_prices: pd.DataFrame  # hourly day-ahead prices of the zone and its neighbours
    source: SourceName
    quality: DataQualityReport
    notices: list[str] = field(default_factory=list)

    @property
    def is_sample(self) -> bool:
        return self.source == "sample"

    @property
    def has_flows(self) -> bool:
        return not self.flows.empty and self.flows["flow_mw"].notna().any()


# ---------------------------------------------------------------------------
# Source resolution
# ---------------------------------------------------------------------------
def store_power_zones() -> list[str]:
    """Zones with ENTSO-E data in the refreshed store (written by scripts/daily_update.py)."""
    return [z for z in POWER_STORE_ZONES if table_path(f"power/{z}").exists()]


def resolve_source(settings: Settings | None = None) -> SourceName:
    """auto: refreshed store if present, else live API if a token is set, else the synthetic sample."""
    settings = settings or get_settings()
    if settings.data_source in ("sample", "entsoe"):
        return settings.data_source
    if settings.data_source == "store" or store_power_zones():
        return "store" if store_power_zones() else "sample"
    return "entsoe" if settings.has_token else "sample"


def available_zones(source: SourceName) -> list[str]:
    if source == "sample":
        return [z for z, cfg in ZONES.items() if cfg.in_sample]
    if source == "store":
        return store_power_zones()
    return list(ZONES)


def store_period(zone: str) -> tuple[date, date]:
    """First and last local delivery day with a day-ahead price in the store."""
    prices = read_table(f"power/{zone}", utc=True)["price"].dropna()
    idx = to_market_tz(prices.index)
    return idx.min().date(), idx.max().date()


def load_store_frame(zone: str) -> pd.DataFrame:
    frame = read_table(f"power/{zone}", utc=True)
    if frame is None:
        raise ValueError(f"No stored ENTSO-E data for {zone}.")
    for col in CORE_COLUMNS:
        if col not in frame:
            frame[col] = float("nan")
    return frame[CORE_COLUMNS].astype(float)


def load_store_flows(zone: str) -> pd.DataFrame:
    wide = read_table("power/flows", utc=True)
    if wide is None or wide.empty:
        return empty_flows()
    cols = [c for c in wide.columns if zone in c.split("->")]
    long = wide[cols].reset_index().melt(id_vars=wide.index.name or "index", var_name="border", value_name="flow_mw")
    long = long.rename(columns={wide.index.name or "index": "timestamp"})
    long[["from_zone", "to_zone"]] = long["border"].str.split("->", expand=True)
    long["timestamp"] = to_market_tz(pd.DatetimeIndex(long["timestamp"]))
    return long[["timestamp", "from_zone", "to_zone", "flow_mw"]].dropna(subset=["flow_mw"]).reset_index(drop=True)


# ---------------------------------------------------------------------------
# Sample data
# ---------------------------------------------------------------------------
@lru_cache(maxsize=None)
def _read_sample_csv(name: str) -> pd.DataFrame:
    path = SAMPLE_DIR / name
    if not path.exists():
        raise FileNotFoundError(
            f"Sample file {path} not found. Run `python scripts/generate_sample_data.py` to create it."
        )
    df = pd.read_csv(path)
    df["timestamp_utc"] = pd.to_datetime(df["timestamp_utc"], utc=True)
    return df


def sample_metadata() -> dict:
    path = SAMPLE_DIR / "metadata.json"
    return json.loads(path.read_text()) if path.exists() else {}


def sample_period() -> tuple[date, date]:
    """First and last local delivery day covered by the sample files."""
    ts = to_market_tz(pd.DatetimeIndex(_read_sample_csv("hourly_prices.csv")["timestamp_utc"].unique()))
    return ts.min().date(), ts.max().date()


def _zone_rows(name: str, zone: str) -> pd.DataFrame:
    df = _read_sample_csv(name)
    out = df[df["zone"] == zone].drop(columns="zone").set_index("timestamp_utc").sort_index()
    out.index.name = "timestamp"
    return out


def load_sample_frame(zone: str) -> pd.DataFrame:
    """Wide hourly frame (UTC index) with the standard column names."""
    prices = _zone_rows("hourly_prices.csv", zone)
    if prices.empty:
        raise ValueError(f"Zone '{zone}' is not part of the sample dataset.")
    ra = _zone_rows("renewable_actual.csv", zone)
    rf = _zone_rows("renewable_forecast.csv", zone)
    frame = pd.DataFrame(
        {
            "price": prices["price_eur_mwh"],
            "load_actual": _zone_rows("load_actual.csv", zone)["load_mw"],
            "load_forecast": _zone_rows("load_forecast.csv", zone)["load_forecast_mw"],
            # Onshore drives availability; offshore is zero where none is installed.
            "wind_actual": ra["wind_onshore_mw"] + ra["wind_offshore_mw"].fillna(0),
            "wind_forecast": rf["wind_onshore_forecast_mw"] + rf["wind_offshore_forecast_mw"].fillna(0),
            "solar_actual": ra["solar_mw"],
            "solar_forecast": rf["solar_forecast_mw"],
        }
    )
    return frame.astype(float)


def load_sample_flows(zone: str) -> pd.DataFrame:
    df = _read_sample_csv("flows.csv")
    df = df[(df["from_zone"] == zone) | (df["to_zone"] == zone)].copy()
    df = df.rename(columns={"timestamp_utc": "timestamp"})
    df["timestamp"] = to_market_tz(pd.DatetimeIndex(df["timestamp"]))
    df["flow_mw"] = df["flow_mw"].astype(float)
    return df.reset_index(drop=True)


def load_sample_prices(zones: list[str]) -> pd.DataFrame:
    df = _read_sample_csv("hourly_prices.csv")
    wide = df[df["zone"].isin(zones)].pivot(index="timestamp_utc", columns="zone", values="price_eur_mwh")
    wide.index = to_market_tz(pd.DatetimeIndex(wide.index))
    wide.index.name = "timestamp"
    wide.columns.name = None
    return wide


# ---------------------------------------------------------------------------
# ENTSO-E data
# ---------------------------------------------------------------------------
def make_client(settings: Settings | None = None) -> EntsoeClient:
    settings = settings or get_settings()
    cache = ResponseCache() if settings.cache_enabled else None
    return EntsoeClient(settings.entsoe_api_token, timeout=settings.request_timeout_s, cache=cache)


def load_entsoe_frame(client: EntsoeClient, zone: str, start, end) -> pd.DataFrame:
    """Download and assemble the wide frame for one zone (native resolution, UTC)."""
    gen = client.get_wind_solar_generation(zone, start, end)
    fc = client.get_wind_solar_forecast(zone, start, end)
    has_offshore = ZONES[zone].has_offshore_wind

    def wind(df: pd.DataFrame, suffix: str) -> pd.Series:
        on = df.get(f"wind_onshore{suffix}", pd.Series(dtype=float))
        off = df.get(f"wind_offshore{suffix}", pd.Series(dtype=float))
        if not has_offshore or off.dropna().empty:
            return on
        return on.add(off, fill_value=0) if not on.dropna().empty else off

    series = {
        "price": client.get_day_ahead_prices(zone, start, end),
        "load_actual": client.get_actual_load(zone, start, end),
        "load_forecast": client.get_load_forecast(zone, start, end),
        "wind_actual": wind(gen, ""),
        "wind_forecast": wind(fc, "_forecast"),
        "solar_actual": gen.get("solar", pd.Series(dtype=float)),
        "solar_forecast": fc.get("solar_forecast", pd.Series(dtype=float)),
    }
    # Every series is averaged to hourly *before* combining, since load,
    # generation and prices may arrive at different resolutions.
    hourly = {k: to_hourly(v) if not v.empty else v for k, v in series.items()}
    frame = pd.concat({k: v for k, v in hourly.items() if not v.empty}, axis=1)
    for col in CORE_COLUMNS:
        if col not in frame:
            frame[col] = float("nan")
    return frame[CORE_COLUMNS]


def load_entsoe_flows(client: EntsoeClient, zone: str, start, end) -> pd.DataFrame:
    rows = []
    for nb in neighbours(zone):
        for a, b in ((zone, nb), (nb, zone)):
            try:
                s = client.get_cross_border_flows(a, b, start, end)
            except EntsoeError as exc:
                logger.warning("Flow %s->%s unavailable: %s", a, b, exc)
                continue
            if s.empty:
                continue
            h = to_hourly(s)
            rows.append(pd.DataFrame({"timestamp": h.index, "from_zone": a, "to_zone": b, "flow_mw": h.to_numpy()}))
    if not rows:
        return empty_flows()
    return pd.concat(rows, ignore_index=True)


def load_entsoe_prices(client: EntsoeClient, zones: list[str], start, end) -> pd.DataFrame:
    cols = {}
    for z in zones:
        try:
            s = client.get_day_ahead_prices(z, start, end)
        except EntsoeError as exc:
            logger.warning("Prices for %s unavailable: %s", z, exc)
            continue
        if not s.empty:
            cols[z] = to_hourly(s)
    return pd.DataFrame(cols)


def empty_flows() -> pd.DataFrame:
    return pd.DataFrame(
        {
            "timestamp": pd.DatetimeIndex([], tz="Europe/Brussels"),
            "from_zone": pd.Series(dtype=object),
            "to_zone": pd.Series(dtype=object),
            "flow_mw": pd.Series(dtype=float),
        }
    )


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------
def load_market_data(
    zone: str,
    start_date,
    end_date,
    warmup_days: int = 45,
    settings: Settings | None = None,
    client: EntsoeClient | None = None,
) -> MarketData:
    """Load, clean and validate data for one zone.

    `warmup_days` of history before `start_date` are included so trailing
    statistics (rolling z-scores, 30-day averages) are defined from the first
    displayed day. Views slice the frame back to [start_date, end_date].
    """
    settings = settings or get_settings()
    source = resolve_source(settings)
    notices: list[str] = []
    start_date = pd.Timestamp(start_date).date()
    end_date = pd.Timestamp(end_date).date()
    load_from = (pd.Timestamp(start_date) - pd.Timedelta(days=warmup_days)).date()

    if source == "entsoe":
        try:
            client = client or make_client(settings)
            start, end = market_day_bounds(load_from, end_date)
            raw = load_entsoe_frame(client, zone, start, end)
            if raw["price"].dropna().empty:
                raise EntsoeError(f"No day-ahead prices returned for {zone} in the selected period.")
            frame, quality = clean_market_frame(raw, load_from, end_date)
            flows = load_entsoe_flows(client, zone, start, end)
            zone_prices = load_entsoe_prices(client, [z for z in neighbours(zone)], start, end)
            zone_prices[zone] = frame["price"]
            return MarketData(zone, frame, flows, zone_prices, "entsoe", quality, notices)
        except EntsoeError as exc:
            if settings.data_source == "entsoe":
                raise
            notices.append(f"ENTSO-E download failed ({exc}). Falling back to the synthetic sample dataset.")
            source = "sample"

    if source == "store":
        if zone not in store_power_zones():
            raise ValueError(f"{zone} has no stored ENTSO-E data yet. Run scripts/daily_update.py with ENTSOE_API_TOKEN.")
        first, last = store_period(zone)
        load_from_c, end_c = max(load_from, first), min(end_date, last)
        if start_date < first or end_date > last:
            notices.append(f"Stored data covers {first} to {last}; the selected range was clipped.")
        frame, quality = clean_market_frame(load_store_frame(zone), load_from_c, end_c)
        flows = load_store_flows(zone)
        flows = flows[(flows["timestamp"] >= frame.index.min()) & (flows["timestamp"] <= frame.index.max())]
        zone_prices = pd.DataFrame({z: to_hourly(load_store_frame(z)["price"]) for z in [zone] + neighbours(zone)
                                    if z in store_power_zones()}).reindex(frame.index)
        return MarketData(zone, frame, flows.reset_index(drop=True), zone_prices, "store", quality, notices)

    # --- sample path -------------------------------------------------------
    if zone not in available_zones("sample"):
        raise ValueError(f"{zone} is only available with an ENTSO-E token (not in the sample dataset).")
    first, last = sample_period()
    load_from_c, end_c = max(load_from, first), min(end_date, last)
    if start_date < first or end_date > last:
        notices.append(f"Sample data covers {first} to {last}; the selected range was clipped.")
    raw = load_sample_frame(zone)
    frame, quality = clean_market_frame(raw, load_from_c, end_c)
    flows = load_sample_flows(zone)
    flows = flows[(flows["timestamp"] >= frame.index.min()) & (flows["timestamp"] <= frame.index.max())]
    zone_prices = load_sample_prices([zone] + [z for z in neighbours(zone) if z in available_zones("sample")])
    zone_prices = zone_prices.reindex(frame.index)
    notices.insert(0, SAMPLE_NOTICE)
    return MarketData(zone, frame, flows.reset_index(drop=True), zone_prices, "sample", quality, notices)
